[2023-09-23 02:35:08,037] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print('REGISTRO: ')
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:35:08,112] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:35:08] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:35:22,599] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:35:22] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:35:22,604] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print("REGISTRO: ")
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:35:22,620] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:35:22] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:36:04,431] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.23.0.2:5000 (Press CTRL+C to quit) - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:36:39,679] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:36:39] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:36:39,748] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:36:39] "POST /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:38:01,463] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:38:01] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:38:01,488] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:38:01] "POST /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:38:55,303] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:38:55] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:38:55,315] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:38:55] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:39:11,647] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:39:11] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:39:11,659] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:39:11] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:43:07,920] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:43:07] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:43:07,931] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:43:07] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:51:37,060] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:51:37] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:51:37,071] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:51:37] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:51:58,167] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:51:58] "OPTIONS / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:51:58,181] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:51:58] "[31m[1mPOST / HTTP/1.1[0m" 401 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:52:57,199] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:52:57] "OPTIONS / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:52:57,213] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:52:57] "[31m[1mPOST / HTTP/1.1[0m" 401 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:53:43,000] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:53:43] "OPTIONS / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:53:43,011] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:53:43] "[31m[1mPOST / HTTP/1.1[0m" 401 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:53:45,764] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:53:45] "POST / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:54:04,399] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:54:04] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:54:04,409] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:54:04] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:54:07,863] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:54:07] "OPTIONS / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:54:07,874] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:54:07] "POST / HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
